package com.icinfo.platform.business.mapper;

import com.icinfo.platform.business.model.BaseInfoArea;

public interface BaseInfoAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info_area
     *
     * @frameworkgenerated
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info_area
     *
     * @frameworkgenerated
     */
    int insert(BaseInfoArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info_area
     *
     * @frameworkgenerated
     */
    int insertSelective(BaseInfoArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info_area
     *
     * @frameworkgenerated
     */
    BaseInfoArea selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info_area
     *
     * @frameworkgenerated
     */
    int updateByPrimaryKeySelective(BaseInfoArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info_area
     *
     * @frameworkgenerated
     */
    int updateByPrimaryKey(BaseInfoArea record);
}