package com.icinfo.platform.application.model;

import java.util.Date;

public class Application {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.ID
     *
     * @frameworkgenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_APP_NAME
     *
     * @frameworkgenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_APP_ICON_URL
     *
     * @frameworkgenerated
     */
    private String appIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_APP_URL
     *
     * @frameworkgenerated
     */
    private String appUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_APP_VERSION
     *
     * @frameworkgenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_APP_CATEGORY_ID
     *
     * @frameworkgenerated
     */
    private String appCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_APP_TYPE
     *
     * @frameworkgenerated
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_BROWSER_TYPE
     *
     * @frameworkgenerated
     */
    private String browserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_SSO_STATUS
     *
     * @frameworkgenerated
     */
    private String ssoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_PUBLISH_STATUS
     *
     * @frameworkgenerated
     */
    private String publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_PUBLISH_DATE
     *
     * @frameworkgenerated
     */
    private Date publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_OPERATOR
     *
     * @frameworkgenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_ORDER_NUMBER
     *
     * @frameworkgenerated
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_CREATE_TIME
     *
     * @frameworkgenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.A_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.ID
     *
     * @return the value of application.ID
     *
     * @frameworkgenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.ID
     *
     * @param id the value for application.ID
     *
     * @frameworkgenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_APP_NAME
     *
     * @return the value of application.A_APP_NAME
     *
     * @frameworkgenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_APP_NAME
     *
     * @param appName the value for application.A_APP_NAME
     *
     * @frameworkgenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_APP_ICON_URL
     *
     * @return the value of application.A_APP_ICON_URL
     *
     * @frameworkgenerated
     */
    public String getAppIconUrl() {
        return appIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_APP_ICON_URL
     *
     * @param appIconUrl the value for application.A_APP_ICON_URL
     *
     * @frameworkgenerated
     */
    public void setAppIconUrl(String appIconUrl) {
        this.appIconUrl = appIconUrl == null ? null : appIconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_APP_URL
     *
     * @return the value of application.A_APP_URL
     *
     * @frameworkgenerated
     */
    public String getAppUrl() {
        return appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_APP_URL
     *
     * @param appUrl the value for application.A_APP_URL
     *
     * @frameworkgenerated
     */
    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl == null ? null : appUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_APP_VERSION
     *
     * @return the value of application.A_APP_VERSION
     *
     * @frameworkgenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_APP_VERSION
     *
     * @param appVersion the value for application.A_APP_VERSION
     *
     * @frameworkgenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_APP_CATEGORY_ID
     *
     * @return the value of application.A_APP_CATEGORY_ID
     *
     * @frameworkgenerated
     */
    public String getAppCategoryId() {
        return appCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_APP_CATEGORY_ID
     *
     * @param appCategoryId the value for application.A_APP_CATEGORY_ID
     *
     * @frameworkgenerated
     */
    public void setAppCategoryId(String appCategoryId) {
        this.appCategoryId = appCategoryId == null ? null : appCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_APP_TYPE
     *
     * @return the value of application.A_APP_TYPE
     *
     * @frameworkgenerated
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_APP_TYPE
     *
     * @param appType the value for application.A_APP_TYPE
     *
     * @frameworkgenerated
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_BROWSER_TYPE
     *
     * @return the value of application.A_BROWSER_TYPE
     *
     * @frameworkgenerated
     */
    public String getBrowserType() {
        return browserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_BROWSER_TYPE
     *
     * @param browserType the value for application.A_BROWSER_TYPE
     *
     * @frameworkgenerated
     */
    public void setBrowserType(String browserType) {
        this.browserType = browserType == null ? null : browserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_SSO_STATUS
     *
     * @return the value of application.A_SSO_STATUS
     *
     * @frameworkgenerated
     */
    public String getSsoStatus() {
        return ssoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_SSO_STATUS
     *
     * @param ssoStatus the value for application.A_SSO_STATUS
     *
     * @frameworkgenerated
     */
    public void setSsoStatus(String ssoStatus) {
        this.ssoStatus = ssoStatus == null ? null : ssoStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_PUBLISH_STATUS
     *
     * @return the value of application.A_PUBLISH_STATUS
     *
     * @frameworkgenerated
     */
    public String getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_PUBLISH_STATUS
     *
     * @param publishStatus the value for application.A_PUBLISH_STATUS
     *
     * @frameworkgenerated
     */
    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus == null ? null : publishStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_PUBLISH_DATE
     *
     * @return the value of application.A_PUBLISH_DATE
     *
     * @frameworkgenerated
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_PUBLISH_DATE
     *
     * @param publishDate the value for application.A_PUBLISH_DATE
     *
     * @frameworkgenerated
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_OPERATOR
     *
     * @return the value of application.A_OPERATOR
     *
     * @frameworkgenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_OPERATOR
     *
     * @param operator the value for application.A_OPERATOR
     *
     * @frameworkgenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_ORDER_NUMBER
     *
     * @return the value of application.A_ORDER_NUMBER
     *
     * @frameworkgenerated
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_ORDER_NUMBER
     *
     * @param orderNumber the value for application.A_ORDER_NUMBER
     *
     * @frameworkgenerated
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_CREATE_TIME
     *
     * @return the value of application.A_CREATE_TIME
     *
     * @frameworkgenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_CREATE_TIME
     *
     * @param createTime the value for application.A_CREATE_TIME
     *
     * @frameworkgenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.A_OPERATE_TIME
     *
     * @return the value of application.A_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.A_OPERATE_TIME
     *
     * @param operateTime the value for application.A_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}