package com.icinfo.platform.quartz.mapper;

import com.icinfo.platform.quartz.model.MyScheduleJob;

public interface MyScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long scheduleJobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int insert(MyScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int insertSelective(MyScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_SCHEDULE_JOB
     *
     * @mbg.generated
     */
    MyScheduleJob selectByPrimaryKey(Long scheduleJobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MyScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MyScheduleJob record);
}