package com.icinfo.platform.quartz.mapper;

import com.icinfo.platform.quartz.model.ScheduleJob;

public interface ScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long scheduleJobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int insert(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int insertSelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbg.generated
     */
    ScheduleJob selectByPrimaryKey(Long scheduleJobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScheduleJob record);
}