package com.icinfo.platform.business.model;

public class BaseInfoArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_info_area.IA_CODE
     *
     * @frameworkgenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_info_area.IA_NAME
     *
     * @frameworkgenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_info_area.IA_LEVEL
     *
     * @frameworkgenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_info_area.IA_PARENT_CODE
     *
     * @frameworkgenerated
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_info_area.IA_INDEXS
     *
     * @frameworkgenerated
     */
    private String indexs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_info_area.IA_CODE
     *
     * @return the value of base_info_area.IA_CODE
     *
     * @frameworkgenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_info_area.IA_CODE
     *
     * @param code the value for base_info_area.IA_CODE
     *
     * @frameworkgenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_info_area.IA_NAME
     *
     * @return the value of base_info_area.IA_NAME
     *
     * @frameworkgenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_info_area.IA_NAME
     *
     * @param name the value for base_info_area.IA_NAME
     *
     * @frameworkgenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_info_area.IA_LEVEL
     *
     * @return the value of base_info_area.IA_LEVEL
     *
     * @frameworkgenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_info_area.IA_LEVEL
     *
     * @param level the value for base_info_area.IA_LEVEL
     *
     * @frameworkgenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_info_area.IA_PARENT_CODE
     *
     * @return the value of base_info_area.IA_PARENT_CODE
     *
     * @frameworkgenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_info_area.IA_PARENT_CODE
     *
     * @param parentCode the value for base_info_area.IA_PARENT_CODE
     *
     * @frameworkgenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_info_area.IA_INDEXS
     *
     * @return the value of base_info_area.IA_INDEXS
     *
     * @frameworkgenerated
     */
    public String getIndexs() {
        return indexs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_info_area.IA_INDEXS
     *
     * @param indexs the value for base_info_area.IA_INDEXS
     *
     * @frameworkgenerated
     */
    public void setIndexs(String indexs) {
        this.indexs = indexs == null ? null : indexs.trim();
    }
}