package com.icinfo.platform.business.model;

import java.util.Date;

public class College {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.ID
     *
     * @frameworkgenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_AREA_ID
     *
     * @frameworkgenerated
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_NAME
     *
     * @frameworkgenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_ENGLISH_NAME
     *
     * @frameworkgenerated
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_ABBREVIATION
     *
     * @frameworkgenerated
     */
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_SET_UP_DATE
     *
     * @frameworkgenerated
     */
    private Date setUpDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_PRINCIPAL
     *
     * @frameworkgenerated
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_ADDRESS
     *
     * @frameworkgenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_PROPERTY
     *
     * @frameworkgenerated
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_AREA
     *
     * @frameworkgenerated
     */
    private Long area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_CREATE_TIME
     *
     * @frameworkgenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_CREATOR
     *
     * @frameworkgenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.C_OPERATOR
     *
     * @frameworkgenerated
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.ID
     *
     * @return the value of college.ID
     *
     * @frameworkgenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.ID
     *
     * @param id the value for college.ID
     *
     * @frameworkgenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_AREA_ID
     *
     * @return the value of college.C_AREA_ID
     *
     * @frameworkgenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_AREA_ID
     *
     * @param areaId the value for college.C_AREA_ID
     *
     * @frameworkgenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_NAME
     *
     * @return the value of college.C_NAME
     *
     * @frameworkgenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_NAME
     *
     * @param name the value for college.C_NAME
     *
     * @frameworkgenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_ENGLISH_NAME
     *
     * @return the value of college.C_ENGLISH_NAME
     *
     * @frameworkgenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_ENGLISH_NAME
     *
     * @param englishName the value for college.C_ENGLISH_NAME
     *
     * @frameworkgenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_ABBREVIATION
     *
     * @return the value of college.C_ABBREVIATION
     *
     * @frameworkgenerated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_ABBREVIATION
     *
     * @param abbreviation the value for college.C_ABBREVIATION
     *
     * @frameworkgenerated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_SET_UP_DATE
     *
     * @return the value of college.C_SET_UP_DATE
     *
     * @frameworkgenerated
     */
    public Date getSetUpDate() {
        return setUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_SET_UP_DATE
     *
     * @param setUpDate the value for college.C_SET_UP_DATE
     *
     * @frameworkgenerated
     */
    public void setSetUpDate(Date setUpDate) {
        this.setUpDate = setUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_PRINCIPAL
     *
     * @return the value of college.C_PRINCIPAL
     *
     * @frameworkgenerated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_PRINCIPAL
     *
     * @param principal the value for college.C_PRINCIPAL
     *
     * @frameworkgenerated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_ADDRESS
     *
     * @return the value of college.C_ADDRESS
     *
     * @frameworkgenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_ADDRESS
     *
     * @param address the value for college.C_ADDRESS
     *
     * @frameworkgenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_PROPERTY
     *
     * @return the value of college.C_PROPERTY
     *
     * @frameworkgenerated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_PROPERTY
     *
     * @param property the value for college.C_PROPERTY
     *
     * @frameworkgenerated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_AREA
     *
     * @return the value of college.C_AREA
     *
     * @frameworkgenerated
     */
    public Long getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_AREA
     *
     * @param area the value for college.C_AREA
     *
     * @frameworkgenerated
     */
    public void setArea(Long area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_CREATE_TIME
     *
     * @return the value of college.C_CREATE_TIME
     *
     * @frameworkgenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_CREATE_TIME
     *
     * @param createTime the value for college.C_CREATE_TIME
     *
     * @frameworkgenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_CREATOR
     *
     * @return the value of college.C_CREATOR
     *
     * @frameworkgenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_CREATOR
     *
     * @param creator the value for college.C_CREATOR
     *
     * @frameworkgenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_OPERATE_TIME
     *
     * @return the value of college.C_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_OPERATE_TIME
     *
     * @param operateTime the value for college.C_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.C_OPERATOR
     *
     * @return the value of college.C_OPERATOR
     *
     * @frameworkgenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.C_OPERATOR
     *
     * @param operator the value for college.C_OPERATOR
     *
     * @frameworkgenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}