package com.icinfo.platform.image.model;

import java.util.Date;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.ID
     *
     * @frameworkgenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_TITLE
     *
     * @frameworkgenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_TYPE
     *
     * @frameworkgenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_INTRODUCE
     *
     * @frameworkgenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_URL
     *
     * @frameworkgenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_CREATE_TIME
     *
     * @frameworkgenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_CREATOR
     *
     * @frameworkgenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.I_OPERATOR
     *
     * @frameworkgenerated
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.ID
     *
     * @return the value of image.ID
     *
     * @frameworkgenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.ID
     *
     * @param id the value for image.ID
     *
     * @frameworkgenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_TITLE
     *
     * @return the value of image.I_TITLE
     *
     * @frameworkgenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_TITLE
     *
     * @param title the value for image.I_TITLE
     *
     * @frameworkgenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_TYPE
     *
     * @return the value of image.I_TYPE
     *
     * @frameworkgenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_TYPE
     *
     * @param type the value for image.I_TYPE
     *
     * @frameworkgenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_INTRODUCE
     *
     * @return the value of image.I_INTRODUCE
     *
     * @frameworkgenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_INTRODUCE
     *
     * @param introduce the value for image.I_INTRODUCE
     *
     * @frameworkgenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_URL
     *
     * @return the value of image.I_URL
     *
     * @frameworkgenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_URL
     *
     * @param url the value for image.I_URL
     *
     * @frameworkgenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_CREATE_TIME
     *
     * @return the value of image.I_CREATE_TIME
     *
     * @frameworkgenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_CREATE_TIME
     *
     * @param createTime the value for image.I_CREATE_TIME
     *
     * @frameworkgenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_CREATOR
     *
     * @return the value of image.I_CREATOR
     *
     * @frameworkgenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_CREATOR
     *
     * @param creator the value for image.I_CREATOR
     *
     * @frameworkgenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_OPERATE_TIME
     *
     * @return the value of image.I_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_OPERATE_TIME
     *
     * @param operateTime the value for image.I_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.I_OPERATOR
     *
     * @return the value of image.I_OPERATOR
     *
     * @frameworkgenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.I_OPERATOR
     *
     * @param operator the value for image.I_OPERATOR
     *
     * @frameworkgenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}