package com.icinfo.platform.quartz.model;

import java.io.Serializable;
import java.util.Date;

public class MyScheduleJob implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.schedule_job_id
     *
     * @mbg.generated
     */
    private Long scheduleJobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.alias_name
     *
     * @mbg.generated
     */
    private String aliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.job_group
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.job_trigger
     *
     * @mbg.generated
     */
    private String jobTrigger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.cron_expression
     *
     * @mbg.generated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.is_sync
     *
     * @mbg.generated
     */
    private Boolean isSync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.class_full_path
     *
     * @mbg.generated
     */
    private String classFullPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.method_name
     *
     * @mbg.generated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_SCHEDULE_JOB.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.schedule_job_id
     *
     * @return the value of MY_SCHEDULE_JOB.schedule_job_id
     * @mbg.generated
     */
    public Long getScheduleJobId() {
        return scheduleJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.schedule_job_id
     *
     * @param scheduleJobId the value for MY_SCHEDULE_JOB.schedule_job_id
     * @mbg.generated
     */
    public void setScheduleJobId(Long scheduleJobId) {
        this.scheduleJobId = scheduleJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.job_name
     *
     * @return the value of MY_SCHEDULE_JOB.job_name
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.job_name
     *
     * @param jobName the value for MY_SCHEDULE_JOB.job_name
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.alias_name
     *
     * @return the value of MY_SCHEDULE_JOB.alias_name
     * @mbg.generated
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.alias_name
     *
     * @param aliasName the value for MY_SCHEDULE_JOB.alias_name
     * @mbg.generated
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName == null ? null : aliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.job_group
     *
     * @return the value of MY_SCHEDULE_JOB.job_group
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.job_group
     *
     * @param jobGroup the value for MY_SCHEDULE_JOB.job_group
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.job_trigger
     *
     * @return the value of MY_SCHEDULE_JOB.job_trigger
     * @mbg.generated
     */
    public String getJobTrigger() {
        return jobTrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.job_trigger
     *
     * @param jobTrigger the value for MY_SCHEDULE_JOB.job_trigger
     * @mbg.generated
     */
    public void setJobTrigger(String jobTrigger) {
        this.jobTrigger = jobTrigger == null ? null : jobTrigger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.status
     *
     * @return the value of MY_SCHEDULE_JOB.status
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.status
     *
     * @param status the value for MY_SCHEDULE_JOB.status
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.cron_expression
     *
     * @return the value of MY_SCHEDULE_JOB.cron_expression
     * @mbg.generated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.cron_expression
     *
     * @param cronExpression the value for MY_SCHEDULE_JOB.cron_expression
     * @mbg.generated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.is_sync
     *
     * @return the value of MY_SCHEDULE_JOB.is_sync
     * @mbg.generated
     */
    public Boolean getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.is_sync
     *
     * @param isSync the value for MY_SCHEDULE_JOB.is_sync
     * @mbg.generated
     */
    public void setIsSync(Boolean isSync) {
        this.isSync = isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.url
     *
     * @return the value of MY_SCHEDULE_JOB.url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.url
     *
     * @param url the value for MY_SCHEDULE_JOB.url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.class_full_path
     *
     * @return the value of MY_SCHEDULE_JOB.class_full_path
     * @mbg.generated
     */
    public String getClassFullPath() {
        return classFullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.class_full_path
     *
     * @param classFullPath the value for MY_SCHEDULE_JOB.class_full_path
     * @mbg.generated
     */
    public void setClassFullPath(String classFullPath) {
        this.classFullPath = classFullPath == null ? null : classFullPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.method_name
     *
     * @return the value of MY_SCHEDULE_JOB.method_name
     * @mbg.generated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.method_name
     *
     * @param methodName the value for MY_SCHEDULE_JOB.method_name
     * @mbg.generated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.params
     *
     * @return the value of MY_SCHEDULE_JOB.params
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.params
     *
     * @param params the value for MY_SCHEDULE_JOB.params
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.description
     *
     * @return the value of MY_SCHEDULE_JOB.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.description
     *
     * @param description the value for MY_SCHEDULE_JOB.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.gmt_create
     *
     * @return the value of MY_SCHEDULE_JOB.gmt_create
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.gmt_create
     *
     * @param gmtCreate the value for MY_SCHEDULE_JOB.gmt_create
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_SCHEDULE_JOB.gmt_modify
     *
     * @return the value of MY_SCHEDULE_JOB.gmt_modify
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_SCHEDULE_JOB.gmt_modify
     *
     * @param gmtModify the value for MY_SCHEDULE_JOB.gmt_modify
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}