package com.icinfo.platform.system.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private static final long serialVersionUID = -7609588222897818992L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @frameworkgenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_LOGIN_NAME
     *
     * @frameworkgenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_PASSWORD
     *
     * @frameworkgenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_REAL_NAME
     *
     * @frameworkgenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_SEX
     *
     * @frameworkgenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_ENCRYPT_SALT
     *
     * @frameworkgenerated
     */
    private String encryptSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_TYPE
     *
     * @frameworkgenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_STATUS
     *
     * @frameworkgenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_CREATE_TIME
     *
     * @frameworkgenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.U_OPERATE_TIME
     *
     * @frameworkgenerated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     * @frameworkgenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     * @frameworkgenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_LOGIN_NAME
     *
     * @return the value of user.U_LOGIN_NAME
     * @frameworkgenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_LOGIN_NAME
     *
     * @param loginName the value for user.U_LOGIN_NAME
     * @frameworkgenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_PASSWORD
     *
     * @return the value of user.U_PASSWORD
     * @frameworkgenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_PASSWORD
     *
     * @param password the value for user.U_PASSWORD
     * @frameworkgenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_REAL_NAME
     *
     * @return the value of user.U_REAL_NAME
     * @frameworkgenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_REAL_NAME
     *
     * @param realName the value for user.U_REAL_NAME
     * @frameworkgenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_SEX
     *
     * @return the value of user.U_SEX
     * @frameworkgenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_SEX
     *
     * @param sex the value for user.U_SEX
     * @frameworkgenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_ENCRYPT_SALT
     *
     * @return the value of user.U_ENCRYPT_SALT
     * @frameworkgenerated
     */
    public String getEncryptSalt() {
        return encryptSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_ENCRYPT_SALT
     *
     * @param encryptSalt the value for user.U_ENCRYPT_SALT
     * @frameworkgenerated
     */
    public void setEncryptSalt(String encryptSalt) {
        this.encryptSalt = encryptSalt == null ? null : encryptSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_TYPE
     *
     * @return the value of user.U_TYPE
     * @frameworkgenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_TYPE
     *
     * @param type the value for user.U_TYPE
     * @frameworkgenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_STATUS
     *
     * @return the value of user.U_STATUS
     * @frameworkgenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_STATUS
     *
     * @param status the value for user.U_STATUS
     * @frameworkgenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_CREATE_TIME
     *
     * @return the value of user.U_CREATE_TIME
     * @frameworkgenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_CREATE_TIME
     *
     * @param createTime the value for user.U_CREATE_TIME
     * @frameworkgenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.U_OPERATE_TIME
     *
     * @return the value of user.U_OPERATE_TIME
     * @frameworkgenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.U_OPERATE_TIME
     *
     * @param operateTime the value for user.U_OPERATE_TIME
     * @frameworkgenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", loginName='" + loginName + '\'' +
                ", password='" + password + '\'' +
                ", realName='" + realName + '\'' +
                ", sex='" + sex + '\'' +
                ", encryptSalt='" + encryptSalt + '\'' +
                ", type='" + type + '\'' +
                ", status='" + status + '\'' +
                ", createTime=" + createTime +
                ", operateTime=" + operateTime +
                '}';
    }
}